{{- $appname := "envoy-gateway-config" }}
{{- if and (has $appname .Values.commonApps) (not (has $appname .Values.excludeApps)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appname }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: k8s-updates
    notifications.argoproj.io/subscribe.on-sync-status-unknown.teams: k8s-updates
    notifications.argoproj.io/subscribe.on-sync-failed.teams: k8s-updates
    notifications.argoproj.io/subscribe.on-health-degraded.teams: k8s-updates
    notifications.argoproj.io/subscribe.on-sync-running.teams: k8s-updates
  labels:
    app.kubernetes.io/part-of: envoy-gateway
    app.kubernetes.io/component: gateway-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: svc/envoy-gateway-config
    repoURL: {{ .Values.cluster.repoURL }}
    {{- if (index .Values.overrides $appname) }}
    targetRevision: {{ get .Values.overrides $appname }}
    {{- else }}
    targetRevision: {{ .Values.cluster.targetRevision }}
    {{- end }}
    helm:
      releaseName: envoy-gateway-config
      parameters: []
      valueFiles:
        - values.yaml
        - {{ include "appofapps.valuePath" . }}
      ignoreMissingValueFiles: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m0s
{{- end }}
